# Tech Access in the USA

## Set up environment

In [1]:
# import modules 
import pandas as pd # data manipulation

## Import data

In [14]:
# import WA data 
educ3 = pd.read_excel("educ3.xlsx", sheet_name = "WA", skiprows = 4, na_values = '-')
# visual check 
educ3.head()

,Unnamed: 0,Unnamed: 1,Device always available for educational purposes,Device usually available for educational purposes,Device sometimes available for educational purposes,Device rarely available for educational purposes,Device never available for educational purposes,Did not report,Internet always available for educational purposes,Internet usually available for educational purposes,Internet sometimes available for educational purposes,Internet rarely available for educational purposes,Internet never available for educational purposes,Did not report.1
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total,1197656.0,933220.0,139098.0,35503.0,38554.0,28752.0,22528.0,895037.0,195150.0,29295.0,23976.0,17025.0,37173.0
2,Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18 - 24,47816.0,31825.0,15991.0,NaN,NaN,NaN,NaN,37615.0,5970.0,NaN,4230.0,NaN,NaN
4,25 - 39,385952.0,300500.0,37236.0,15024.0,6647.0,20267.0,6277.0,295690.0,59704.0,5900.0,2017.0,16923.0,5718.0

In [38]:
# Check that sums of columns equal total
educ3.iloc[1,1] == sum(educ3.iloc[1,2:8]) # check not passed

False

In [39]:
# Sums to 1 less than total 
sum(educ3.iloc[1,2:8])

1197655.0

In [41]:
# Double checked with manual sum and has same result 
933220 + 139098 + 35503 + 38554 + 28752 + 22528 == sum(educ3.iloc[1,2:8]) # check passed

True

In [129]:
# Calculate percent respondents 
incomes = educ3.iloc[36:41,2:14].div(educ3.iloc[36:41,1], axis=0)
# Insert first column with group names 
incomes.insert(0, "Group", educ3.iloc[36:41,0], True) 
incomes

,Group,Device always available for educational purposes,Device usually available for educational purposes,Device sometimes available for educational purposes,Device rarely available for educational purposes,Device never available for educational purposes,Did not report,Internet always available for educational purposes,Internet usually available for educational purposes,Internet sometimes available for educational purposes,Internet rarely available for educational purposes,Internet never available for educational purposes,Did not report.1
36,Internet provided by… *,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,"Internet, Children’s school or school dist...",0.786385,0.155150,0.058465,NaN,NaN,NaN,0.772300,NaN,0.072550,0.155150,NaN,NaN
38,Someone in household or family or belongs ...,0.809273,0.124474,0.031380,0.030943,0.003095,0.000836,0.780438,0.180593,0.025433,0.013537,NaN,NaN
39,Some other source,0.817478,0.008759,NaN,0.173762,NaN,NaN,0.818836,NaN,0.007401,0.173762,NaN,NaN
40,Did not report,0.427918,0.001238,NaN,NaN,0.308392,0.262465,0.342193,NaN,NaN,NaN,0.206634,0.451172

In [125]:
# Calculate percent respondents 
incomes = educ3.iloc[45:49,2:14].div(educ3.iloc[45:49,1], axis=0)
# Insert first column with group names 
incomes.insert(0, "Group", educ3.iloc[45:49,0], True) 
incomes

,Group,Device always available for educational purposes,Device usually available for educational purposes,Device sometimes available for educational purposes,Device rarely available for educational purposes,Device never available for educational purposes,Did not report,Internet always available for educational purposes,Internet usually available for educational purposes,Internet sometimes available for educational purposes,Internet rarely available for educational purposes,Internet never available for educational purposes,Did not report.1
45,Respondent currently employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Yes,0.823167,0.084833,0.028211,0.021497,0.022103,0.020188,0.763221,0.157299,0.013168,0.01535,0.022103,0.028859
47,No,0.700479,0.172096,0.032270,0.051284,0.027456,0.016412,0.718389,0.173414,0.044595,0.02837,0.000237,0.034995
48,Did not report,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN

In [123]:
# Calculate percent respondents 
incomes = educ3.iloc[50:55,2:14].div(educ3.iloc[50:55,1], axis=0)
# Insert first column with group names 
incomes.insert(0, "Group", educ3.iloc[50:55,0], True) 
incomes

,Group,Device always available for educational purposes,Device usually available for educational purposes,Device sometimes available for educational purposes,Device rarely available for educational purposes,Device never available for educational purposes,Did not report,Internet always available for educational purposes,Internet usually available for educational purposes,Internet sometimes available for educational purposes,Internet rarely available for educational purposes,Internet never available for educational purposes,Did not report.1
50,Enough of the types of food wanted,0.811326,0.117474,0.013356,0.026034,0.004202,0.027608,0.809966,0.137337,0.019246,0.006148,0.000128,0.027176
51,"Enough food, but not always the types wanted",0.761217,0.100566,0.048877,0.033360,0.054190,0.001790,0.617019,0.226323,0.036158,0.044724,0.054190,0.021586
52,Sometimes not enough to eat,0.568654,0.188064,0.026956,0.100914,0.115398,NaN,0.663679,0.119982,0.026956,0.069606,NaN,0.119777
53,Often not enough to eat,0.440558,0.026806,0.532565,NaN,NaN,NaN,0.506457,0.444258,0.049284,NaN,NaN,NaN
54,Did not report,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN

In [121]:
# The $25K-34,999 group not as expected -- were they provided assistance? 
# Calculate percent respondents 
incomes = educ3.iloc[56:65,2:14].div(educ3.iloc[56:65,1], axis=0)
# Insert first column with group names 
incomes.insert(0, "Group", educ3.iloc[56:65,0], True) 
incomes

,Group,Device always available for educational purposes,Device usually available for educational purposes,Device sometimes available for educational purposes,Device rarely available for educational purposes,Device never available for educational purposes,Did not report,Internet always available for educational purposes,Internet usually available for educational purposes,Internet sometimes available for educational purposes,Internet rarely available for educational purposes,Internet never available for educational purposes,Did not report.1
56,"Less than $25,000",0.571619,0.197231,0.068728,0.060755,0.095521,0.006156,0.553636,0.250047,0.021089,0.078243,NaN,0.096986
57,"$25,000 - $34,999",0.825530,0.114088,0.050638,0.009745,NaN,NaN,0.671898,0.323708,0.004394,NaN,NaN,NaN
58,"$35,000 - $49,999",0.589425,0.127518,0.036892,0.050003,0.196172,NaN,0.578277,0.078033,0.128349,0.050003,0.165338,NaN
59,"$50,000 - $74,999",0.785515,0.143059,0.065844,0.005582,NaN,NaN,0.589750,0.375265,0.034986,NaN,NaN,NaN
60,"$75,000 - $99,999",0.827573,0.103305,NaN,0.069122,NaN,NaN,0.901198,0.073986,0.010388,0.013740,0.000695,NaN
61,"$100,000 - $149,999",0.857675,0.064689,0.016878,0.060758,NaN,NaN,0.849782,0.103074,0.008485,0.038659,NaN,NaN
62,"$150,000 - $199,999",0.883609,0.070506,0.042614,NaN,NaN,0.003261,0.914544,0.077474,0.007982,NaN,NaN,NaN
63,"$200,000 and above",0.806397,0.184329,0.005532,0.003743,NaN,NaN,0.829951,0.151171,0.018878,NaN,NaN,NaN
64,Did not report,0.624428,0.025125,0.003275,NaN,NaN,0.347172,0.538506,0.006117,NaN,NaN,NaN,0.455393