# Tech Access in the USA

## Purpose

This Jupyter Notebook reads in Excel files that have been manually downloaded from the U.S. Census website: https://www.census.gov/programs-surveys/household-pulse-survey/data.html 

These files contain data from the Household Pulse Survey, "designed to quickly and efficiently deploy data collected on how peopleâ€™s lives have been impacted by the COVID-19 pandemic."

Specifically, this notebook reads in files from different weeks of data collection around technology access in families with children and extracts data from Washington State. We retain only rows that record technology access by different income groups. The data from different weeks are appended to the same dataframe and exported as a CSV file.

## Set up environment

In [1]:
# import modules 
import pandas as pd # data manipulation
from datetime import datetime # handling dates

## Import data

### Income

In [3]:
# Initialize list of file names 
file_names = ["educ3_050520.xlsx", "educ3_051220.xlsx", "educ3_051920.xlsx", "educ3_052620.xlsx"]

locations = ["WA", "Seattle_Metro_Area"]


# Initialize empty dataframe 
income_df = pd.DataFrame()

# Loop through files to extract data
for i in range(0, len(file_names)):
    # Loop through locations to select sheet
    for j in range(0, len(locations)):
        # Read sheet from Excel file 
        file = pd.read_excel(file_names[i], sheet_name = locations[j], skiprows = 4, na_values = '-')
        # Extract income rows
        income = file.iloc[56:65,2:14]
        # Add column to specify location
        income.insert(0, "Location", locations[j])
        # Add column to specify date
        income.insert(1, "Date", [file_names[i][6:12]]*9, True) 
        # Add column to specify income group 
        income.insert(2, "Group", file.iloc[56:65,0], True) 
        # Add column to specify total surveyed 
        income.insert(3, "Total", file.iloc[56:65,1], True)
        # Append to dataframe
        income_df = income_df.append(income)

# Show dataframe
income_df

,Location,Date,Group,Total,Device always available for educational purposes,Device usually available for educational purposes,Device sometimes available for educational purposes,Device rarely available for educational purposes,Device never available for educational purposes,Did not report,Internet always available for educational purposes,Internet usually available for educational purposes,Internet sometimes available for educational purposes,Internet rarely available for educational purposes,Internet never available for educational purposes,Did not report.1
56,WA,050520,"Less than $25,000",126801.0,82138.0,23821.0,15521.0,2661.0,2661.0,NaN,72749.0,43280.0,5450.0,2661.0,2661.0,NaN
57,WA,050520,"$25,000 - $34,999",142422.0,91223.0,34196.0,9156.0,7026.0,820.0,NaN,91048.0,30024.0,10628.0,9902.0,820.0,NaN
58,WA,050520,"$35,000 - $49,999",137649.0,104024.0,14927.0,2928.0,5103.0,10666.0,NaN,107465.0,19518.0,NaN,NaN,10666.0,NaN
59,WA,050520,"$50,000 - $74,999",250272.0,152880.0,62590.0,18203.0,16598.0,NaN,NaN,180698.0,42946.0,26627.0,NaN,NaN,NaN
60,WA,050520,"$75,000 - $99,999",125245.0,93336.0,20611.0,4813.0,6485.0,NaN,NaN,79949.0,39671.0,5625.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Seattle_Metro_Area,052620,"$75,000 - $99,999",79481.0,69395.0,10086.0,NaN,NaN,NaN,NaN,72598.0,5523.0,1257.0,NaN,102.0,NaN
61,Seattle_Metro_Area,052620,"$100,000 - $149,999",126916.0,118355.0,7226.0,457.0,877.0,NaN,NaN,111580.0,15336.0,NaN,NaN,NaN,NaN
62,Seattle_Metro_Area,052620,"$150,000 - $199,999",63847.0,54419.0,7437.0,1646.0,NaN,NaN,344.0,57682.0,5322.0,842.0,NaN,NaN,NaN
63,Seattle_Metro_Area,052620,"$200,000 and above",140252.0,108925.0,29637.0,1008.0,682.0,NaN,NaN,115003.0,24561.0,688.0,NaN,NaN,NaN
64,Seattle_Metro_Area,052620,Did not report,40768.0,31087.0,1388.0,204.0,NaN,NaN,8088.0,25735.0,204.0,NaN,NaN,NaN,14829.0

### Food security

In [16]:
# Initialize empty dataframe 
food_df = pd.DataFrame()

# Loop through files to extract data
for i in range(0, len(file_names)):
    # Loop through locations to select sheet
    for j in range(0, len(locations)):
        # Read sheet from Excel file 
        file = pd.read_excel(file_names[i], sheet_name = locations[j], skiprows = 4, na_values = '-')
        # Extract income rows
        food = file.iloc[50:55,2:14]
        # Add column to specify location
        food.insert(0, "Location", locations[j])
        # Add column to specify date
        food.insert(1, "Date", [file_names[i][6:12]]*5, True)
        # Add column to specify income group 
        food.insert(2, "Group", file.iloc[50:55,0], True) 
        # Add column to specify total surveyed 
        food.insert(3, "Total", file.iloc[50:55,1], True)
        # Append to dataframe
        food_df = food_df.append(food)

# Show dataframe
food_df

,Location,Date,Group,Total,Device always available for educational purposes,Device usually available for educational purposes,Device sometimes available for educational purposes,Device rarely available for educational purposes,Device never available for educational purposes,Did not report,Internet always available for educational purposes,Internet usually available for educational purposes,Internet sometimes available for educational purposes,Internet rarely available for educational purposes,Internet never available for educational purposes,Did not report.1
50,WA,050520,Enough of the types of food wanted,1044897.0,816638.0,168218.0,29909.0,10885.0,9657.0,9590.0,841228.0,148759.0,31229.0,2661.0,9657.0,11364.0
51,WA,050520,"Enough food, but not always the types wanted",248673.0,136434.0,57694.0,38066.0,5865.0,10615.0,NaN,143298.0,82212.0,8851.0,3698.0,10615.0,NaN
52,WA,050520,Sometimes not enough to eat,92317.0,44759.0,19709.0,57.0,25079.0,2713.0,NaN,46648.0,17878.0,16598.0,6205.0,4990.0,NaN
53,WA,050520,Often not enough to eat,2462.0,2462.0,NaN,NaN,NaN,NaN,NaN,241.0,2221.0,NaN,NaN,NaN,NaN
54,WA,050520,Did not report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Seattle_Metro_Area,050520,Enough of the types of food wanted,590820.0,482647.0,82515.0,17460.0,6782.0,1416.0,NaN,489087.0,89364.0,10953.0,NaN,1416.0,NaN
51,Seattle_Metro_Area,050520,"Enough food, but not always the types wanted",99431.0,63980.0,22930.0,11699.0,822.0,NaN,NaN,72007.0,16085.0,7641.0,3698.0,NaN,NaN
52,Seattle_Metro_Area,050520,Sometimes not enough to eat,33153.0,14354.0,7547.0,57.0,8482.0,2713.0,NaN,16243.0,5716.0,NaN,6205.0,4990.0,NaN
53,Seattle_Metro_Area,050520,Often not enough to eat,2221.0,2221.0,NaN,NaN,NaN,NaN,NaN,NaN,2221.0,NaN,NaN,NaN,NaN
54,Seattle_Metro_Area,050520,Did not report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,WA,051220,Enough of the types of food wanted,897021.0,693587.0,129503.0,14633.0,2037.0,30442.0,26819.0,742125.0,82408.0,1202.0,4079.0,42709.0,24499.0
51,WA,051220,"Enough food, but not always the types wanted",248131.0,156898.0,40204.0,22775.0,27041.0,NaN,1213.0,181292.0,56872.0,8754.0,NaN,NaN,1213.0
52,WA,051220,Sometimes not enough to eat,121997.0,61137.0,19262.0,37238.0,NaN,NaN,4361.0,71096.0,13663.0,37238.0,NaN,NaN,NaN
53,WA,051220,Often not enough to eat,29201.0,NaN,4518.0,NaN,24684.0,NaN,NaN,NaN,4518.0,24684.0,NaN,NaN,NaN
54,WA,051220,Did not report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Seattle_Metro_Area,051220,Enough of the types of food wanted,530133.0,440906.0,57356.0,8586.0,2037.0,2523.0,18724.0,453870.0,39788.0,1202.0,1392.0,14791.0,19090.0
51,Seattle_Metro_Area,051220,"Enough food, but not always the types wanted",123473.0,104015.0,12908.0,2757.0,2580.0,NaN,1213.0,91146.0,29145.0,1969.0,NaN,NaN,1213.0
52,Seattle_Metro_Area,051220,Sometimes not enough to eat,8500.0,4139.0,NaN,NaN,NaN,NaN,4361.0,4361.0,4139.0,NaN,NaN,NaN,NaN
53,Seattle_Metro_Area,051220,Often not enough to eat,24684.0,NaN,NaN,NaN,24684.0,NaN,NaN,NaN,NaN,24684.0,NaN,NaN,NaN
54,Seattle_Metro_Area,051220,Did not report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,WA,051920,Enough of the types of food wanted,1016666.0,728762.0,180253.0,36659.0,7120.0,63457.0,415.0,792827.0,113337.0,39629.0,451.0,66038.0,4384.0
51,WA,051920,"Enough food, but not always the types wanted",238280.0,207495.0,24416.0,5339.0,740.0,290.0,NaN,208772.0,17134.0,11653.0,347.0,19.0,355.0
52,WA,051920,Sometimes not enough to eat,75616.0,19449.0,6075.0,29256.0,20409.0,426.0,NaN,20575.0,4285.0,30055.0,19516.0,1185.0,NaN
53,WA,051920,Often not enough to eat,16463.0,NaN,934.0,12482.0,3046.0,NaN,NaN,444.0,491.0,15528.0,NaN,NaN,NaN
54,WA,051920,Did not report,779.0,779.0,NaN,NaN,NaN,NaN,NaN,779.0,NaN,NaN,NaN,NaN,NaN
50,Seattle_Metro_Area,051920,Enough of the types of food wanted,504290.0,420112.0,59019.0,21829.0,414.0,2500.0,415.0,452587.0,40734.0,4486.0,NaN,2500.0,3983.0
51,Seattle_Metro_Area,051920,"Enough food, but not always the types wanted",106088.0,92562.0,11106.0,1391.0,740.0,290.0,NaN,95532.0,7181.0,2720.0,281.0,19.0,355.0
52,Seattle_Metro_Area,051920,Sometimes not enough to eat,28100.0,12790.0,1562.0,4650.0,8905.0,193.0,NaN,13296.0,1176.0,4665.0,8012.0,951.0,NaN
53,Seattle_Metro_Area,051920,Often not enough to eat,15972.0,NaN,444.0,12482.0,3046.0,NaN,NaN,444.0,NaN,15528.0,NaN,NaN,NaN
54,Seattle_Metro_Area,051920,Did not report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,WA,052620,Enough of the types of food wanted,795743.0,645607.0,93479.0,10628.0,20716.0,3344.0,21969.0,644525.0,109285.0,15315.0,4892.0,102.0,21625.0
51,WA,052620,"Enough food, but not always the types wanted",312292.0,237722.0,31406.0,15264.0,10418.0,16923.0,559.0,192690.0,70679.0,11292.0,13967.0,16923.0,6741.0
52,WA,052620,Sometimes not enough to eat,73528.0,41812.0,13828.0,1982.0,7420.0,8485.0,NaN,48799.0,8822.0,1982.0,5118.0,NaN,8807.0
53,WA,052620,Often not enough to eat,14325.0,6311.0,384.0,7629.0,NaN,NaN,NaN,7255.0,6364.0,706.0,NaN,NaN,NaN
54,WA,052620,Did not report,1768.0,1768.0,NaN,NaN,NaN,NaN,NaN,1768.0,NaN,NaN,NaN,NaN,NaN
50,Seattle_Metro_Area,052620,Enough of the types of food wanted,412103.0,323925.0,66940.0,5708.0,3752.0,3344.0,8433.0,326456.0,66935.0,7646.0,2875.0,102.0,8088.0
51,Seattle_Metro_Area,052620,"Enough food, but not always the types wanted",166679.0,147704.0,13356.0,4378.0,682.0,NaN,559.0,143563.0,15106.0,1268.0,NaN,NaN,6741.0
52,Seattle_Metro_Area,052620,Sometimes not enough to eat,46300.0,22004.0,13828.0,1982.0,NaN,8485.0,NaN,26689.0,8822.0,1982.0,NaN,NaN,8807.0
53,Seattle_Metro_Area,052620,Often not enough to eat,13122.0,5108.0,384.0,7629.0,NaN,NaN,NaN,6052.0,6364.0,706.0,NaN,NaN,NaN
54,Seattle_Metro_Area,052620,Did not report,1768.0,1768.0,NaN,NaN,NaN,NaN,NaN,1768.0,NaN,NaN,NaN,NaN,NaN

In [17]:
# Convert date columns to date object
income_df["Date"] = pd.to_datetime(income_df["Date"], format = '%m%d%y')
food_df["Date"] = pd.to_datetime(food_df["Date"], format = '%m%d%y')

In [18]:
# Save to CSV 
income_df.to_csv('educ3_income_multitime.csv', index=False)
food_df.to_csv('educ3_food_multitime.csv', index=False)